version: "3"
services:
  nzbtoproxy:
    build: ./docker/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
    networks:
      - nzbproxy
    environment:
      - TZ='Europe/Berlin'

  torproxy:
    image: dperson/torproxy
    ports:
      - "9050:9050"
    networks:
      - nzbproxy
    depends_on:
      - nzbtoproxy
    environment:
      - TZ='Europe/Berlin'

networks:
  nzbproxy:
    driver: bridge
